// <auto-generated />
using System;
using DataServer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataServer.Migrations
{
    [DbContext(typeof(MapDbContext))]
    [Migration("20201208165317_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DataServer.Models.Place", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("addedByuserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("addedByuserId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("DataServer.Models.Review", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Placeid")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("addedByuserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("comment")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("Placeid");

                    b.HasIndex("addedByuserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("DataServer.Models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("auth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataServer.Models.UserData", b =>
                {
                    b.Property<long>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("DataServer.Models.Place", b =>
                {
                    b.HasOne("DataServer.Models.UserData", "addedBy")
                        .WithMany()
                        .HasForeignKey("addedByuserId");

                    b.Navigation("addedBy");
                });

            modelBuilder.Entity("DataServer.Models.Review", b =>
                {
                    b.HasOne("DataServer.Models.Place", null)
                        .WithMany("reviews")
                        .HasForeignKey("Placeid");

                    b.HasOne("DataServer.Models.UserData", "addedBy")
                        .WithMany()
                        .HasForeignKey("addedByuserId");

                    b.Navigation("addedBy");
                });

            modelBuilder.Entity("DataServer.Models.Place", b =>
                {
                    b.Navigation("reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
